export interface TourPackage {
    packageID?: number; // Optional because it might be auto-generated by the backend
    packageName: string;
    description: string;
    price: number;
    durationDays: number;
    place: string;
    createdAt?: Date; // Optional because it might be set by the backend
    updatedAt?: Date; // Optional because it might be set by the backend
  }